# Generated by Django 4.2.11 on 2024-04-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=10)),
                ('lastName', models.CharField(max_length=10)),
                ('transaction', models.CharField(max_length=10)),
                ('stock', models.CharField(max_length=10)),
                ('filed', models.DateField()),
                ('traded', models.DateField()),
            ],
        ),
    ]
